/usr/bin/python3: can't find '__main__' module in 'generate_mapping'
